### ISSUE TITLE
Pi-Hole Icon change

### ISSUE THREAD

**Issue by milandzuris** [bastgau/ha-pi-hole-v6#8]
Hi. please change Icon Pi-Hole to this one in .png format.

https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png

**Comment by milandzuris** [comment]
![Image](https://github.com/user-attachments/assets/fcf202bd-a5cf-4dc8-92ea-12531ca414d2)

**Comment by PromoFaux** [comment]
@bastgau - https://github.com/pi-hole/graphics/blob/master/Vortex/Vortex_with_Wordmark.svg

**Comment by msandvold** [comment]
I changed the icon for these update.xxxx enteties in customize.yaml since I do not know hvere to find the source for the icon in this integration.
```
update.xxxxxx_core_update_available:
  entity_picture: /local/pi-hole.png

update.xxxxxx__ftl_update_available:
  entity_picture: /local/pi-hole.png

update.xxxxxx__web_update_available:
  entity_picture: /local/pi-hole.png
```
