### ISSUE TITLE
Trying to make timed block disable work

### ISSUE THREAD

**Issue by WybeBosch** [bastgau/ha-pi-hole-v6#82]
Hey there, in the previous integration i had , this card that allowed me to disable blocking for x minutes. 
But i cant seem to find the new proper "service" to call. Am i missing something? 
should the name of the service be different? 

is my api call incorrect? 
```yaml
action: call-service
      service: pi_hole.disable
      service_data:
        entity_id: switch.pi_hole
        duration: "3000"
```

The global on/off switch does seem to work tho

![Image](https://github.com/user-attachments/assets/4e5c3c4a-08e6-40fc-824e-da9f046f3e57)

```yaml
type: custom:bubble-card
card_type: button
entity: switch.pi_hole
button_type: state
sub_button:
  - entity: switch.pi_hole
    tap_action:
      action: call-service
      service: pi_hole.disable
      service_data:
        entity_id: switch.pi_hole
        duration: "3000"
      target:
        entity_id: switch.pi_hole
    name: 5m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole
    tap_action:
      action: call-service
      service: pi_hole.disable
      service_data:
        entity_id: switch.pi_hole
        duration: "00:30:00"
      target:
        entity_id: switch.pi_hole
    name: 30m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole
    tap_action:
      action: call-service
      service: pi_hole.disable
      service_data:
        entity_id: switch.pi_hole
        duration: "00:01:00"
      target:
        entity_id: switch.pi_hole
    name: 60m
    show_name: true
    icon: mdi:block-helper
card_layout: large
scrolling_effect: false
force_icon: false
show_name: false
show_state: true
show_last_changed: true
tap_action:
  action: more-info
  service: ""
  target:
    entity_id: switch.pi_hole
styles: |2
    .is-on .bubble-button-card-container {
      background-color: #0000;
      border-radius: 10px;
  }
    .bubble-icon-container {
      opacity: 1 !important;
      background-color: ${state === 'on' ? 'green' : 'darkred'} !important;
  }
    .bubble-sub-button-1 {
      background: 00000;
    }
      .bubble-sub-button-2 {
      background: 00000;
    }
      .bubble-sub-button-3 {
      background: 00000;
    }
      .bubble-sub-button-4 {
      background: 00000;
    }
button_action:
  tap_action:
    action: toggle

```

**Comment by cuttyhunk** [comment]
@WybeBosch me and my pal ChatGPT just got it working. 

![Image](https://github.com/user-attachments/assets/ab11441a-5378-4a07-afba-46ab7172a1cd)

![Image](https://github.com/user-attachments/assets/85c3849e-51a6-4967-9837-9d1545f56c60)

`type: custom:bubble-card
card_type: button
entity: switch.pi_hole_2
button_type: state
card_layout: large
scrolling_effect: false
force_icon: false
show_name: false
show_state: true
show_last_changed: true
tap_action:
  action: more-info
styles: |
  .is-on .bubble-button-card-container {
    background-color: #0000;
    border-radius: 10px;
  }
  .bubble-icon-container {
    opacity: 1 !important;
    background-color: ${state === 'on' ? 'green' : 'darkred'} !important;
  }
  .bubble-sub-button-1,
  .bubble-sub-button-2,
  .bubble-sub-button-3 {
    background: #000000;
  }
button_action:
  tap_action:
    action: toggle
sub_button:
  - entity: switch.pi_hole_2
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "00:05:00"
      target:
        entity_id: switch.pi_hole_2
    name: 5m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole_2
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "00:30:00"
      target:
        entity_id: switch.pi_hole_2
    name: 30m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole_2
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "01:00:00"
      target:
        entity_id: switch.pi_hole_2
    name: 60m
    show_name: true
    icon: mdi:block-helper`

**Comment by WybeBosch** [comment]
Ahh.. your chatgpt beat my chatgpt. I had thrown github copilot on it, since it had access to the repo. 
but it seems it didnt understand to update the service to pi_hole_v6. 

Thanks :D 

This ended up being my final version 

```yaml
type: custom:bubble-card
card_type: button
entity: switch.pi_hole
button_type: state
sub_button:
  - entity: switch.pi_hole
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "00:05:00"
      target:
        entity_id: switch.pi_hole
    name: 5m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "00:30:00"
      target:
        entity_id: switch.pi_hole
    name: 30m
    show_name: true
    icon: mdi:block-helper
  - entity: switch.pi_hole_2
    tap_action:
      action: call-service
      service: pi_hole_v6.disable
      service_data:
        duration: "01:00:00"
      target:
        entity_id: switch.pi_hole
    name: 60m
    show_name: true
    icon: mdi:block-helper
card_layout: large
scrolling_effect: false
force_icon: false
show_name: false
show_state: true
show_last_changed: true
tap_action:
  action: more-info
  service: ""
  target:
    entity_id: switch.pi_hole
styles: |2
    .is-on .bubble-button-card-container {
      background-color: #0000;
      border-radius: 10px;
  }
    .bubble-icon-container {
      opacity: 1 !important;
      background-color: ${state === 'on' ? 'green' : 'darkred'} !important;
  }
    .bubble-sub-button-1 {
      background: 00000;
    }
      .bubble-sub-button-2 {
      background: 00000;
    }
      .bubble-sub-button-3 {
      background: 00000;
    }
      .bubble-sub-button-4 {
      background: 00000;
    }
button_action:
  tap_action:
    action: toggle

```
